pipeline {
 agent any

 stages {

  stage('Clone'){
   steps{
    git 'https://github.com/pitchikakumaraveeravenkataganesh/cybercars-devops-project.git'
   }
  }

  stage('Install'){
   steps{
    sh 'cd frontend && npm install'
   }
  }

  stage('Build'){
   steps{
    sh 'cd frontend && npm run build'
   }
  }

  stage('Deploy'){
   steps{
    sh '''
    sudo rm -rf /var/www/html/*
    sudo cp -r frontend/out/* /var/www/html/
    '''
   }
  }

 }
}

